-- MySQL Script generated by MySQL Workbench
-- 04/21/16 13:39:18
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema materfood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `materfood` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `materfood` ;

-- -----------------------------------------------------
-- Table `materfood`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `materfood`.`receita` (
  `cod` INT(6) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `ingredientes` TEXT NOT NULL,
  `modopreparo` TEXT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
